repos:
-   repo: local
    hooks:
      - id: isort
        name: isort
        entry: pipenv run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: pipenv run black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: pipenv run mypy .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: .flake8
        name: .flake8
        entry: pipenv run .flake8
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      -   id: debug-statements
