name: linter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2
    - name: Set up Python environment 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev --deploy
    - name: Lint the code
      run: |
        python -m flake8
        python -m mypy .
        python -m black --diff --check --fast .
