name: linter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2
    - name: Set up Python environment 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev --deploy
        pipenv run pip install black==24.1.1 click==8.1.7
    - name: Lint the code
      run: |
        python -m pipenv run flake8 src/
        python -m pipenv run mypy src/
        python -m pipenv run black --diff --check --fast src/
